#!/bin/bash
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

/usr/libexec/gsd-xsettings &
feh --bg-fill --no-fehbg ~/.local/share/backgrounds/key2.png &
picom --config ~/.config/picom/picom.conf &
xss-lock -n 'bash /usr/share/doc/xss-lock/dim-screen.sh' -- ~/.config/lock-screen.sh -n &

~/.config/touchpad.sh &
~/.config/polybar/launch_polybar.sh &
~/.config/ulauncher/launch_ulauncher.sh &

xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width 0
bspc config window_gap 10

bspc config normal_border_color "#212121"
bspc config focused_border_color "#424242"

bspc config split_ratio 0.6
bspc config focus_follows_pointer	true
bspc config pointer_modifier mod1
 
bspc config automatic_scheme alternate
