require("bufferline").setup({
	animations = true,
	auto_hide = true,
	icons = true,
	icon_custom_color = true,
	icon_separator_active = "▎",
	icon_separator_inactive = "▎",
	clickable = false,
	closable = false,
	insert_at_end = false,
	insert_at_start = false,
	no_name_title = nil,
	maximum_padding = 1,
	maximum_length = 32,
})
