vim.cmd("nnoremap <C-t> :NERDTreeToggle<CR>")
vim.cmd("nnoremap <C-f> :NERDTreeFocus<CR>")
vim.cmd("noremap <C-z> :undo<CR>")
vim.cmd("noremap <C-r> :redo<CR>")
vim.cmd("inoremap <C-z> <Esc>:undo<CR>")
vim.cmd("inoremap <C-r> :redo<CR>")
vim.cmd("vnoremap <C-z> :undo<CR>")
vim.cmd("vnoremap <C-r> :redo<CR>")
vim.cmd("nmap <C-a> gg<S-v>G")
vim.cmd("nmap <S-Up> v<Up>")
vim.cmd("nmap <S-Down> v<Down>")
vim.cmd("nmap <S-Left> v<Left>")
vim.cmd("nmap <S-Right> v<Right>")
vim.cmd("vmap <S-Up> <Up>")
vim.cmd("vmap <S-Down> <Down>")
vim.cmd("vmap <S-Left> <Left>")
vim.cmd("vmap <S-Right> <Right>")
vim.cmd("imap <S-Up> <Esc>v<Up>")
vim.cmd("imap <S-Down> <Esc>v<Down>")
vim.cmd("imap <S-Left> <Esc>v<Left>")
vim.cmd("imap <S-Right> <Esc>v<Right>")
vim.cmd("nnoremap <leader>d '_d")
vim.cmd("nnoremap x '_x")
vim.cmd("nmap <S-Tab> :tabprev<Return>")
vim.cmd("nmap <Tab> :tabnext<Return>")
vim.cmd("vmap <C-c> y<Esc>i")
vim.cmd("vmap <C-x> d<Esc>i")
vim.cmd("map <C-v> pi")
vim.cmd("imap <C-v> <Esc>pi")
vim.cmd("nmap <C-A-Down> <PageDown>")
vim.cmd("nmap <C-A-Up> <PageUp>")
vim.cmd("vmap <C-A-Down> <PageDown>")
vim.cmd("vmap <C-A-Up> <PageUp>")
vim.cmd("imap <C-A-Down> <PageDown>")
vim.cmd("imap <C-A-Up> <PageUp>")
vim.cmd("nmap <C-Space> :Telescope find_files<CR>")
vim.cmd("vmap <C-Space> :Telescope find_files<CR>")

vim.cmd("set nocompatible")
vim.cmd("set nu rnu")
vim.cmd("set shortmess+=c")
vim.cmd("set smartindent")
vim.cmd("set nowrap")
vim.cmd("set expandtab")
vim.cmd("set title")
vim.cmd("set hlsearch")
vim.cmd("set showcmd")
vim.cmd("set ignorecase")
vim.cmd("set cursorline")
vim.cmd("set lazyredraw")
vim.cmd("filetype plugin indent on")
vim.cmd("set ai")
vim.cmd("set completeopt=menuone,noinsert,noselect")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set cmdheight=1")
vim.cmd("set updatetime=50")
vim.cmd("set signcolumn=yes")
vim.cmd("set laststatus=2")
vim.cmd("set scrolloff=10")
vim.cmd("set mouse=a")
